#

In [1]:
import pandas as pd
import torch

In [2]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [15]:
pd.set_option('display.max_columns', None)

In [3]:
#Census_Sample.xlsx
file_path = "/home/mangosteen/papaya/ece-5464/project_4/Census_Supplement_Data.xlsx"
df = pd.read_excel(file_path)

In [4]:
df.head()

,HSUP_WGT,MARSUPWT,FSUP_WGT,HWCVAL,HSSVAL,HFDVAL,HDISVAL,HDIVVAL,AGI,FTOTVAL,...,A_USLHRS,A_AGE,PAW_YN,PAW_MON,A_SEX,PEINUSYR,WKSWORK,A_MARITL,PENATVTY,HAS_DIV
0,687.71,646.86,687.71,0,13200,0,0,0,0,27100,...,-1,78,2,0,2,0,0,4,57,0
1,1516.95,1516.95,1516.95,0,0,0,0,0,80819,106123,...,40,65,2,0,2,0,52,1,57,0
2,1516.95,1516.95,1516.95,0,0,0,0,0,0,106123,...,40,66,2,0,1,0,49,1,57,0
3,1516.95,2208.61,1516.95,0,0,0,0,0,25304,106123,...,40,28,2,0,1,0,52,7,57,0
4,1483.56,1483.56,1483.56,0,17340,0,0,0,0,17340,...,-1,72,2,0,1,0,0,4,57,0

In [5]:
drop_columns = ["HSUP_WGT", "MARSUPWT", "FSUP_WGT","AGI"]
y = df["AGI"]
df= df.drop(columns = drop_columns)

In [6]:
y.head()

0        0
1    80819
2        0
3    25304
4        0
Name: AGI, dtype: int64

In [7]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 HWCVAL        0
HSSVAL        0
HFDVAL        0
HDISVAL       0
HDIVVAL       0
FTOTVAL       0
STATETAX_A    0
A_USLHRS      0
A_AGE         0
PAW_YN        0
PAW_MON       0
A_SEX         0
PEINUSYR      0
WKSWORK       0
A_MARITL      0
PENATVTY      0
HAS_DIV       0
dtype: int64

In [8]:
num_zero = df.map(lambda x: x == 0)
zero_count = num_zero.sum()
print("Number of 0 values per column:\n", zero_count)

Number of 0 values per column:
 HWCVAL        99219
HSSVAL        75614
HFDVAL        88177
HDISVAL       97931
HDIVVAL       67045
FTOTVAL        2148
STATETAX_A    69212
A_USLHRS         52
A_AGE           930
PAW_YN        20790
PAW_MON       99588
A_SEX             0
PEINUSYR      85824
WKSWORK       49227
A_MARITL          0
PENATVTY          0
HAS_DIV       67045
dtype: int64

In [9]:
drop_these = ["HWCVAL", "HSSVAL", "HFDVAL", "HDISVAL", "HDIVVAL", "STATETAX_A", "PAW_MON","PEINUSYR","HAS_DIV"]
df = df.drop(columns = drop_these)

In [10]:
df.head()

   FTOTVAL  A_USLHRS  A_AGE  PAW_YN  A_SEX  WKSWORK  A_MARITL  PENATVTY
0    27100        -1     78       2      2        0         4        57
1   106123        40     65       2      2       52         1        57
2   106123        40     66       2      1       49         1        57
3   106123        40     28       2      1       52         7        57
4    17340        -1     72       2      1        0         4        57

In [13]:
categorical_cols = ['PAW_YN', 'A_MARITL', 'PENATVTY']
df[categorical_cols] = df[categorical_cols].astype('category')
x_df = pd.get_dummies(df, columns=categorical_cols)

In [16]:
x_df.head()

,FTOTVAL,A_USLHRS,A_AGE,A_SEX,WKSWORK,PAW_YN_0,PAW_YN_1,PAW_YN_2,A_MARITL_1,A_MARITL_2,A_MARITL_3,A_MARITL_4,A_MARITL_5,A_MARITL_6,A_MARITL_7,PENATVTY_57,PENATVTY_60,PENATVTY_66,PENATVTY_69,PENATVTY_73,PENATVTY_78,PENATVTY_100,PENATVTY_102,PENATVTY_103,PENATVTY_104,PENATVTY_105,PENATVTY_106,PENATVTY_108,PENATVTY_109,PENATVTY_110,PENATVTY_116,PENATVTY_117,PENATVTY_118,PENATVTY_119,PENATVTY_120,PENATVTY_126,PENATVTY_127,PENATVTY_128,PENATVTY_129,PENATVTY_130,PENATVTY_132,PENATVTY_134,PENATVTY_136,PENATVTY_137,PENATVTY_138,PENATVTY_139,PENATVTY_140,PENATVTY_142,PENATVTY_147,PENATVTY_148,PENATVTY_149,PENATVTY_150,PENATVTY_151,PENATVTY_152,PENATVTY_154,PENATVTY_155,PENATVTY_156,PENATVTY_157,PENATVTY_158,PENATVTY_159,PENATVTY_160,PENATVTY_161,PENATVTY_162,PENATVTY_163,PENATVTY_164,PENATVTY_165,PENATVTY_166,PENATVTY_168,PENATVTY_200,PENATVTY_202,PENATVTY_203,PENATVTY_205,PENATVTY_206,PENATVTY_207,PENATVTY_209,PENATVTY_210,PENATVTY_211,PENATVTY_212,PENATVTY_213,PENATVTY_214,PENATVTY_215,PENATVTY_216,PENATVTY_217,PENATVTY_218,PENATVTY_220,PENATVTY_222,PENATVTY_223,PENATVTY_224,PENATVTY_226,PENATVTY_228,PENATVTY_229,PENATVTY_231,PENATVTY_233,PENATVTY_235,PENATVTY_236,PENATVTY_238,PENATVTY_239,PENATVTY_240,PENATVTY_242,PENATVTY_243,PENATVTY_245,PENATVTY_246,PENATVTY_247,PENATVTY_248,PENATVTY_249,PENATVTY_300,PENATVTY_301,PENATVTY_303,PENATVTY_310,PENATVTY_311,PENATVTY_312,PENATVTY_313,PENATVTY_314,PENATVTY_315,PENATVTY_316,PENATVTY_321,PENATVTY_323,PENATVTY_324,PENATVTY_327,PENATVTY_328,PENATVTY_329,PENATVTY_330,PENATVTY_332,PENATVTY_333,PENATVTY_338,PENATVTY_339,PENATVTY_340,PENATVTY_341,PENATVTY_343,PENATVTY_360,PENATVTY_361,PENATVTY_362,PENATVTY_363,PENATVTY_364,PENATVTY_365,PENATVTY_368,PENATVTY_369,PENATVTY_370,PENATVTY_372,PENATVTY_373,PENATVTY_374,PENATVTY_399,PENATVTY_400,PENATVTY_407,PENATVTY_408,PENATVTY_412,PENATVTY_414,PENATVTY_416,PENATVTY_417,PENATVTY_421,PENATVTY_423,PENATVTY_425,PENATVTY_427,PENATVTY_429,PENATVTY_430,PENATVTY_436,PENATVTY_440,PENATVTY_444,PENATVTY_447,PENATVTY_448,PENATVTY_449,PENATVTY_451,PENATVTY_453,PENATVTY_454,PENATVTY_457,PENATVTY_459,PENATVTY_460,PENATVTY_461,PENATVTY_462,PENATVTY_501,PENATVTY_508,PENATVTY_511,PENATVTY_512,PENATVTY_515,PENATVTY_523,PENATVTY_527,PENATVTY_555
0,27100,-1,78,2,0,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,106123,40,65,2,52,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,106123,40,66,1,49,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,106123,40,28,1,52,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,17340,-1,72,1,0,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
from sklearn.preprocessing import MinMaxScaler

# Assume these are the final one-hot encoded columns
X = x_df # Predicting this?
y = y

# Scale everything in X (not y)
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [18]:
from sklearn.neural_network import MLPClassifier