In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model as linmod
from sklearn import preprocessing as preproc 
from sklearn.preprocessing import MinMaxScaler

In [2]:
file_path = "/home/mangosteen/papaya/ece-5464/project_4/VWXYZ.xlsx"

In [3]:
df = pd.read_excel(file_path)

In [4]:
df.head()

          V          W          X         Y   Z  Binary
0  0.022843  89.916823  35.224993  0.892337  52       0
1  0.071389  78.297509  25.982185  0.401186  94       0
2  0.047956  96.304442  43.930283  1.236431  73       0
3  0.010650  50.831579  10.122295  0.189904  55       1
4  0.036211  12.713869  16.723924  0.311530  91       1

In [5]:
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 V         0
W         0
X         0
Y         0
Z         0
Binary    0
dtype: int64

In [6]:
question_marks = df.map(lambda x: x == "?")
question_mark_count = question_marks.sum()
print("Number of '?' values per column:\n", question_mark_count)

Number of '?' values per column:
 V         0
W         0
X         0
Y         0
Z         0
Binary    0
dtype: int64

In [7]:
X = df.drop(columns=["Binary"]) 
Y = df["Binary"]

In [8]:
X_og = X
scaler = MinMaxScaler()
X_scaled_og = pd.DataFrame(scaler.fit_transform(X_og), columns=X_og.columns)

In [9]:
X_scaled_og.head()

          V         W         X         Y     Z
0  0.000122  0.899176  0.782778  0.446160  0.04
1  0.000607  0.782980  0.577380  0.200580  0.88
2  0.000373  0.963054  0.976232  0.618209  0.46
3  0.000000  0.508314  0.224933  0.094937  0.10
4  0.000255  0.127128  0.371638  0.155751  0.82

In [10]:
poly = preproc.PolynomialFeatures(2)
X_poly = poly.fit_transform(X)
feature_names = poly.get_feature_names_out(X.columns)
X_poly_df = pd.DataFrame(X_poly, columns=feature_names)
scaler = MinMaxScaler()
X_scaled_poly = pd.DataFrame(scaler.fit_transform(X_poly_df), columns=X_poly_df.columns)

In [11]:
X_scaled_poly.head()

,1,V,W,X,Y,Z,V^2,V W,V X,V Y,...,W^2,W X,W Y,W Z,X^2,X Y,X Z,Y^2,Y Z,Z^2
0,0.0,0.000122,0.899176,0.782778,0.446160,0.04,4.075775e-08,0.000206,0.000174,0.000097,...,0.808520,0.707792,0.404055,0.467978,0.612745,0.350318,0.407085,0.199067,0.232344,0.0272
1,0.0,0.000607,0.782980,0.577380,0.200580,0.88,4.973243e-07,0.000560,0.000409,0.000138,...,0.613062,0.454608,0.158184,0.736647,0.333372,0.116172,0.542795,0.040237,0.188829,0.8448
2,0.0,0.000373,0.963054,0.976232,0.618209,0.46,2.182124e-07,0.000463,0.000465,0.000292,...,0.927473,0.945419,0.599635,0.703643,0.953029,0.605364,0.712723,0.382190,0.451961,0.3772
3,0.0,0.000000,0.508314,0.224933,0.094937,0.10,0.000000e+00,0.000054,0.000019,0.000005,...,0.258390,0.114981,0.048611,0.279816,0.050598,0.021423,0.123724,0.009016,0.052291,0.0700
4,0.0,0.000255,0.127128,0.371638,0.155751,0.82,1.195501e-07,0.000046,0.000130,0.000051,...,0.016165,0.047514,0.019945,0.115792,0.138119,0.058065,0.338227,0.024263,0.141948,0.7708

In [12]:
X_log = X.apply(lambda col: np.log(col))
X_combined = pd.concat([X, X_log.add_suffix("_log")], axis=1)
scaler = MinMaxScaler()
X_scaled_log = pd.DataFrame(scaler.fit_transform(X_combined), columns=X_combined.columns)

In [13]:
X_scaled_log.head()

,V,W,X,Y,Z,V_log,W_log,X_log,Y_log,Z_log
0,0.000122,0.899176,0.782778,0.446160,0.04,0.083412,0.990495,0.978807,0.926881,0.056584
1,0.000607,0.782980,0.577380,0.200580,0.88,0.207971,0.978119,0.952471,0.854455,0.910733
2,0.000373,0.963054,0.976232,0.618209,0.46,0.164482,0.996633,0.997918,0.956429,0.545968
3,0.000000,0.508314,0.224933,0.094937,0.10,0.000000,0.939481,0.870896,0.786695,0.137504
4,0.000255,0.127128,0.371638,0.155751,0.82,0.133775,0.815534,0.914346,0.831540,0.863938

In [14]:
X_poly_log = pd.concat([X_poly_df,X_log.add_suffix("_log")], axis=1)
X_scaled_poly_log = pd.DataFrame(scaler.fit_transform(X_poly_log), columns = X_poly_log.columns)

In [15]:
X_scaled_poly_log.head()

,1,V,W,X,Y,Z,V^2,V W,V X,V Y,...,X Y,X Z,Y^2,Y Z,Z^2,V_log,W_log,X_log,Y_log,Z_log
0,0.0,0.000122,0.899176,0.782778,0.446160,0.04,4.075775e-08,0.000206,0.000174,0.000097,...,0.350318,0.407085,0.199067,0.232344,0.0272,0.083412,0.990495,0.978807,0.926881,0.056584
1,0.0,0.000607,0.782980,0.577380,0.200580,0.88,4.973243e-07,0.000560,0.000409,0.000138,...,0.116172,0.542795,0.040237,0.188829,0.8448,0.207971,0.978119,0.952471,0.854455,0.910733
2,0.0,0.000373,0.963054,0.976232,0.618209,0.46,2.182124e-07,0.000463,0.000465,0.000292,...,0.605364,0.712723,0.382190,0.451961,0.3772,0.164482,0.996633,0.997918,0.956429,0.545968
3,0.0,0.000000,0.508314,0.224933,0.094937,0.10,0.000000e+00,0.000054,0.000019,0.000005,...,0.021423,0.123724,0.009016,0.052291,0.0700,0.000000,0.939481,0.870896,0.786695,0.137504
4,0.0,0.000255,0.127128,0.371638,0.155751,0.82,1.195501e-07,0.000046,0.000130,0.000051,...,0.058065,0.338227,0.024263,0.141948,0.7708,0.133775,0.815534,0.914346,0.831540,0.863938

In [16]:
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


X_list = [
    ("Original", X_scaled_og),
    ("Polynomial", X_scaled_poly),
    ("Log-transformed", X_scaled_log),
    ("Poly + Log", X_scaled_poly_log)
]

for name, features in X_list:
    X = features
    y = Y
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22222)

    reg = LogisticRegression(max_iter=1000).fit(X_train, y_train)
    y_pred = reg.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, reg.predict_proba(X_test)[:, 1])
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    tpr = tp / (tp + fn)
    tnr = tn / (tn + fp)
    fpr = fp / (fp + tn)
    fnr = fn / (fn + tp)

    print(f"Classification test set: [{name}] iterations, accuracy = {accuracy:.4f}, AUC = {auc:.4f}")
    print(f"Precision = {precision:.6f}, Recall = {recall:.6f}")
    print(cm)
    print(f"TPR = {tpr:.4f}, FNR = {fnr:.4f}, FPR = {fpr:.4f}, TNR = {tnr:.4f}")
    print("-" * 60)

Classification test set: [Original] iterations, accuracy = 0.8426, AUC = 0.9259
Precision = 0.846758, Recall = 0.848997
[[12115  2382]
 [ 2341 13162]]
TPR = 0.8490, FNR = 0.1510, FPR = 0.1643, TNR = 0.8357
------------------------------------------------------------
Classification test set: [Polynomial] iterations, accuracy = 0.8435, AUC = 0.9266
Precision = 0.847693, Recall = 0.849771
[[12130  2367]
 [ 2329 13174]]
TPR = 0.8498, FNR = 0.1502, FPR = 0.1633, TNR = 0.8367
------------------------------------------------------------
Classification test set: [Log-transformed] iterations, accuracy = 0.8427, AUC = 0.9262
Precision = 0.846495, Recall = 0.849771
[[12108  2389]
 [ 2329 13174]]
TPR = 0.8498, FNR = 0.1502, FPR = 0.1648, TNR = 0.8352
------------------------------------------------------------
Classification test set: [Poly + Log] iterations, accuracy = 0.8439, AUC = 0.9267
Precision = 0.848592, Recall = 0.849578
[[12147  2350]
 [ 2332 13171]]
TPR = 0.8496, FNR = 0.1504, FPR = 0.1621, TNR = 0.8379
------------------------------------------------------------