In [1]:
import pandas as pd
import numpy as np
import sklearn
import torch

#### List of Questions
- Part 1.. Does this number look right?
- Why are there two tabs? One is Batting and the other is Salaries. DO you load two tabs? or use only the first one?
- what is for each year present in the dataset mean? If we're only using first tab, are we conducting two linear regression prediction, one with the whole tab, the other one with the same tab but divided into each year?
- What does diviing that dataset into year mean? If we have 1985 to 1989, does it mean it is divided into 5 datasets?

In [2]:
torch.cuda.is_available()

True

In [3]:
# No truncating results
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

In [5]:
file_path = '/home/joong/orange/ece-5464/project_3/data/BattingSalariesData.xlsx'
df_batting = pd.read_excel(file_path, sheet_name = "Batting")
df_salaries= pd.read_excel(file_path, sheet_name = "Salaries")
print(df_batting.shape, df_salaries.shape)

(45174, 24) (26428, 6)

In [16]:
df_batting.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,yearPlayer,Salary
0,aasedo01,1985,1,BAL,AL,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1985aasedo01,NaN
1,abregjo01,1985,1,CHN,NL,6,9,0,0,0,0,0,1,0,0,0,2,0,0,0,0,0,1985abregjo01,NaN
2,ackerji01,1985,1,TOR,AL,61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1985ackerji01,170000.0
3,adamsri02,1985,1,SFN,NL,54,121,12,23,3,1,2,10,1,1,5,23,3,1,3,0,2,1985adamsri02,NaN
4,agostju01,1985,1,CHA,AL,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1985agostju01,147500.0

In [17]:
df_salaries.head()

   yearID teamID lgID   playerID   yearPlayerID  salary
0    1985    TOR   AL  ackerji01  1985ackerji01  170000
1    1985    CHA   AL  agostju01  1985agostju01  147500
2    1985    PHI   NL  aguaylu01  1985aguaylu01  237000
3    1985    TOR   AL  alexado01  1985alexado01  875000
4    1985    SLN   NL  allenne01  1985allenne01  750000

In [23]:
# remove the ones without salary! 
filtered_df_batting = df_batting.dropna(subset=["Salary"])

In [24]:
filtered_df_batting.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,yearPlayer,Salary
2,ackerji01,1985,1,TOR,AL,61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1985ackerji01,170000.0
4,agostju01,1985,1,CHA,AL,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1985agostju01,147500.0
5,aguaylu01,1985,1,PHI,NL,91,165,27,46,7,3,6,21,1,0,22,26,5,6,4,3,7,1985aguaylu01,237000.0
8,alexado01,1985,1,TOR,AL,36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1985alexado01,875000.0
10,allenne01,1985,1,SLN,NL,23,2,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1985allenne01,750000.0

# Don't Forget To Normalize Data!!

In [ ]:
# example.. import before using this 
scaler = skpreporc.MinMaxScaler()